subject=["C++","C","Java","Python","C","C"]

subject.append("JavaScript")
subject.insert(2,"Node.js")
print(subject)
subject.remove("Node.js")
subject.sort()
subject.reverse()
subject.pop()
subject2=subject.copy()
subject.clear()
print(subject)
print(subject2)
print(subject2.index("C"))
print(subject2.count("C"))